" Vim syntax file
" Language:	C++ STL
" Maintainer:	Mizuchi <ytj000@gmail.com>
"
" This script is aimed at making STL (and boost) user has the most readable
" highlight. Not just highlight all STL functions and types. So some syntax
" was commented out, this is intentional. For example, std::bitset::any is a
" function, however boost::any is a type. In order to avoid confusion, "any"
" should not be hightlighted.
"
" This list is not complete yet. Your contribution is welcome!

syntax keyword cppConstant badbit
syntax keyword cppConstant cerr
syntax keyword cppConstant cin
syntax keyword cppConstant clog
syntax keyword cppConstant cout
syntax keyword cppConstant digits
syntax keyword cppConstant digits10
syntax keyword cppConstant eofbit
syntax keyword cppConstant failbit
syntax keyword cppConstant goodbit
syntax keyword cppConstant has_denorm
syntax keyword cppConstant has_denorm_loss
syntax keyword cppConstant has_infinity
syntax keyword cppConstant has_quiet_NaN
syntax keyword cppConstant has_signaling_NaN
syntax keyword cppConstant is_bounded
syntax keyword cppConstant is_exact
syntax keyword cppConstant is_iec559
syntax keyword cppConstant is_integer
syntax keyword cppConstant is_modulo
syntax keyword cppConstant is_signed
syntax keyword cppConstant is_specialized
syntax keyword cppConstant max_digits10
syntax keyword cppConstant max_exponent
syntax keyword cppConstant max_exponent10
syntax keyword cppConstant min_exponent
syntax keyword cppConstant min_exponent10
syntax keyword cppConstant nothrow
syntax keyword cppConstant npos
syntax keyword cppConstant radix
syntax keyword cppConstant round_style
syntax keyword cppConstant tinyness_before
syntax keyword cppConstant traps
syntax keyword cppConstant wcerr
syntax keyword cppConstant wcin
syntax keyword cppConstant wclog
syntax keyword cppConstant wcout
syntax keyword cppConstant PRId16
syntax keyword cppConstant PRId32
syntax keyword cppConstant PRId64
syntax keyword cppConstant PRId8
syntax keyword cppConstant PRIdFAST16
syntax keyword cppConstant PRIdFAST32
syntax keyword cppConstant PRIdFAST64
syntax keyword cppConstant PRIdFAST8
syntax keyword cppConstant PRIdLEAST16
syntax keyword cppConstant PRIdLEAST32
syntax keyword cppConstant PRIdLEAST64
syntax keyword cppConstant PRIdLEAST8
syntax keyword cppConstant PRIdMAX
syntax keyword cppConstant PRIdPTR
syntax keyword cppConstant PRIi16
syntax keyword cppConstant PRIi32
syntax keyword cppConstant PRIi64
syntax keyword cppConstant PRIi8
syntax keyword cppConstant PRIiFAST16
syntax keyword cppConstant PRIiFAST32
syntax keyword cppConstant PRIiFAST64
syntax keyword cppConstant PRIiFAST8
syntax keyword cppConstant PRIiLEAST16
syntax keyword cppConstant PRIiLEAST32
syntax keyword cppConstant PRIiLEAST64
syntax keyword cppConstant PRIiLEAST8
syntax keyword cppConstant PRIiMAX
syntax keyword cppConstant PRIiPTR
syntax keyword cppConstant PRIo16
syntax keyword cppConstant PRIo32
syntax keyword cppConstant PRIo64
syntax keyword cppConstant PRIo8
syntax keyword cppConstant PRIoFAST16
syntax keyword cppConstant PRIoFAST32
syntax keyword cppConstant PRIoFAST64
syntax keyword cppConstant PRIoFAST8
syntax keyword cppConstant PRIoLEAST16
syntax keyword cppConstant PRIoLEAST32
syntax keyword cppConstant PRIoLEAST64
syntax keyword cppConstant PRIoLEAST8
syntax keyword cppConstant PRIoMAX
syntax keyword cppConstant PRIoPTR
syntax keyword cppConstant PRIu16
syntax keyword cppConstant PRIu32
syntax keyword cppConstant PRIu64
syntax keyword cppConstant PRIu8
syntax keyword cppConstant PRIuFAST16
syntax keyword cppConstant PRIuFAST32
syntax keyword cppConstant PRIuFAST64
syntax keyword cppConstant PRIuFAST8
syntax keyword cppConstant PRIuLEAST16
syntax keyword cppConstant PRIuLEAST32
syntax keyword cppConstant PRIuLEAST64
syntax keyword cppConstant PRIuLEAST8
syntax keyword cppConstant PRIuMAX
syntax keyword cppConstant PRIuPTR
syntax keyword cppConstant PRIx16
syntax keyword cppConstant PRIX16
syntax keyword cppConstant PRIx32
syntax keyword cppConstant PRIX32
syntax keyword cppConstant PRIx64
syntax keyword cppConstant PRIX64
syntax keyword cppConstant PRIx8
syntax keyword cppConstant PRIX8
syntax keyword cppConstant PRIxFAST16
syntax keyword cppConstant PRIXFAST16
syntax keyword cppConstant PRIxFAST32
syntax keyword cppConstant PRIXFAST32
syntax keyword cppConstant PRIxFAST64
syntax keyword cppConstant PRIXFAST64
syntax keyword cppConstant PRIxFAST8
syntax keyword cppConstant PRIXFAST8
syntax keyword cppConstant PRIxLEAST16
syntax keyword cppConstant PRIXLEAST16
syntax keyword cppConstant PRIxLEAST32
syntax keyword cppConstant PRIXLEAST32
syntax keyword cppConstant PRIxLEAST64
syntax keyword cppConstant PRIXLEAST64
syntax keyword cppConstant PRIxLEAST8
syntax keyword cppConstant PRIXLEAST8
syntax keyword cppConstant PRIxMAX
syntax keyword cppConstant PRIXMAX
syntax keyword cppConstant PRIxPTR
syntax keyword cppConstant PRIXPTR
syntax keyword cppConstant SCNd16
syntax keyword cppConstant SCNd32
syntax keyword cppConstant SCNd64
syntax keyword cppConstant SCNd8
syntax keyword cppConstant SCNdFAST16
syntax keyword cppConstant SCNdFAST32
syntax keyword cppConstant SCNdFAST64
syntax keyword cppConstant SCNdFAST8
syntax keyword cppConstant SCNdLEAST16
syntax keyword cppConstant SCNdLEAST32
syntax keyword cppConstant SCNdLEAST64
syntax keyword cppConstant SCNdLEAST8
syntax keyword cppConstant SCNdMAX
syntax keyword cppConstant SCNdPTR
syntax keyword cppConstant SCNi16
syntax keyword cppConstant SCNi32
syntax keyword cppConstant SCNi64
syntax keyword cppConstant SCNi8
syntax keyword cppConstant SCNiFAST16
syntax keyword cppConstant SCNiFAST32
syntax keyword cppConstant SCNiFAST64
syntax keyword cppConstant SCNiFAST8
syntax keyword cppConstant SCNiLEAST16
syntax keyword cppConstant SCNiLEAST32
syntax keyword cppConstant SCNiLEAST64
syntax keyword cppConstant SCNiLEAST8
syntax keyword cppConstant SCNiMAX
syntax keyword cppConstant SCNiPTR
syntax keyword cppConstant SCNo16
syntax keyword cppConstant SCNo32
syntax keyword cppConstant SCNo64
syntax keyword cppConstant SCNo8
syntax keyword cppConstant SCNoFAST16
syntax keyword cppConstant SCNoFAST32
syntax keyword cppConstant SCNoFAST64
syntax keyword cppConstant SCNoFAST8
syntax keyword cppConstant SCNoLEAST16
syntax keyword cppConstant SCNoLEAST32
syntax keyword cppConstant SCNoLEAST64
syntax keyword cppConstant SCNoLEAST8
syntax keyword cppConstant SCNoMAX
syntax keyword cppConstant SCNoPTR
syntax keyword cppConstant SCNu16
syntax keyword cppConstant SCNu32
syntax keyword cppConstant SCNu64
syntax keyword cppConstant SCNu8
syntax keyword cppConstant SCNuFAST16
syntax keyword cppConstant SCNuFAST32
syntax keyword cppConstant SCNuFAST64
syntax keyword cppConstant SCNuFAST8
syntax keyword cppConstant SCNuLEAST16
syntax keyword cppConstant SCNuLEAST32
syntax keyword cppConstant SCNuLEAST64
syntax keyword cppConstant SCNuLEAST8
syntax keyword cppConstant SCNuMAX
syntax keyword cppConstant SCNuPTR
syntax keyword cppConstant SCNx16
syntax keyword cppConstant SCNX16
syntax keyword cppConstant SCNx32
syntax keyword cppConstant SCNX32
syntax keyword cppConstant SCNx64
syntax keyword cppConstant SCNX64
syntax keyword cppConstant SCNx8
syntax keyword cppConstant SCNX8
syntax keyword cppConstant SCNxFAST16
syntax keyword cppConstant SCNXFAST16
syntax keyword cppConstant SCNxFAST32
syntax keyword cppConstant SCNXFAST32
syntax keyword cppConstant SCNxFAST64
syntax keyword cppConstant SCNXFAST64
syntax keyword cppConstant SCNxFAST8
syntax keyword cppConstant SCNXFAST8
syntax keyword cppConstant SCNxLEAST16
syntax keyword cppConstant SCNXLEAST16
syntax keyword cppConstant SCNxLEAST32
syntax keyword cppConstant SCNXLEAST32
syntax keyword cppConstant SCNxLEAST64
syntax keyword cppConstant SCNXLEAST64
syntax keyword cppConstant SCNxLEAST8
syntax keyword cppConstant SCNXLEAST8
syntax keyword cppConstant SCNxMAX
syntax keyword cppConstant SCNXMAX
syntax keyword cppConstant SCNxPTR
syntax keyword cppConstant SCNXPTR
syntax keyword cppExceptions bad_alloc
syntax keyword cppExceptions bad_array_new_length
syntax keyword cppExceptions bad_exception
syntax keyword cppExceptions bad_typeid bad_cast
syntax keyword cppExceptions domain_error
syntax keyword cppExceptions exception
syntax keyword cppExceptions invalid_argument
syntax keyword cppExceptions length_error
syntax keyword cppExceptions logic_error
syntax keyword cppExceptions out_of_range
syntax keyword cppExceptions overflow_error
syntax keyword cppExceptions range_error
syntax keyword cppExceptions runtime_error
syntax keyword cppExceptions underflow_error
syntax keyword cppSTLfunction abort
syntax keyword cppSTLfunction abs
syntax keyword cppSTLfunction accumulate
syntax keyword cppSTLfunction acos
syntax keyword cppSTLfunction adjacent_difference
syntax keyword cppSTLfunction adjacent_find
syntax keyword cppSTLfunction adjacent_find_if
syntax keyword cppSTLfunction advance
syntax keyword cppSTLfunctional binary_function
syntax keyword cppSTLfunctional binary_negate
syntax keyword cppSTLfunctional bit_and
syntax keyword cppSTLfunctional bit_not
syntax keyword cppSTLfunctional bit_or
syntax keyword cppSTLfunctional divides
syntax keyword cppSTLfunctional equal_to
syntax keyword cppSTLfunctional greater
syntax keyword cppSTLfunctional greater_equal
syntax keyword cppSTLfunctional less
syntax keyword cppSTLfunctional less_equal
syntax keyword cppSTLfunctional logical_and
syntax keyword cppSTLfunctional logical_not
syntax keyword cppSTLfunctional logical_or
syntax keyword cppSTLfunctional minus
syntax keyword cppSTLfunctional modulus
syntax keyword cppSTLfunctional multiplies
syntax keyword cppSTLfunctional negate
syntax keyword cppSTLfunctional not_equal_to
syntax keyword cppSTLfunctional plus
syntax keyword cppSTLfunctional unary_function
syntax keyword cppSTLfunctional unary_negate
"syntax keyword cppSTLfunction any
syntax keyword cppSTLfunction append
syntax keyword cppSTLfunction arg
syntax keyword cppSTLfunction asctime
syntax keyword cppSTLfunction asin
syntax keyword cppSTLfunction assert
syntax keyword cppSTLfunction assign
syntax keyword cppSTLfunction at
syntax keyword cppSTLfunction atan
syntax keyword cppSTLfunction atan2
syntax keyword cppSTLfunction atexit
syntax keyword cppSTLfunction atof
syntax keyword cppSTLfunction atoi
syntax keyword cppSTLfunction atol
syntax keyword cppSTLfunction atoll
syntax keyword cppSTLfunction back
syntax keyword cppSTLfunction back_inserter
syntax keyword cppSTLfunction bad
syntax keyword cppSTLfunction beg
syntax keyword cppSTLfunction begin
syntax keyword cppSTLfunction binary_compose
syntax keyword cppSTLfunction binary_negate
syntax keyword cppSTLfunction binary_search
syntax keyword cppSTLfunction bind1st
syntax keyword cppSTLfunction bind2nd
syntax keyword cppSTLfunction binder1st
syntax keyword cppSTLfunction binder2nd
syntax keyword cppSTLfunction bsearch
syntax keyword cppSTLfunction calloc
syntax keyword cppSTLfunction capacity
syntax keyword cppSTLfunction ceil
syntax keyword cppSTLfunction clear
syntax keyword cppSTLfunction clearerr
syntax keyword cppSTLfunction clock
syntax keyword cppSTLfunction close
syntax keyword cppSTLfunction compare
syntax keyword cppSTLfunction conj
syntax keyword cppSTLfunction construct
syntax keyword cppSTLfunction copy
syntax keyword cppSTLfunction copy_backward
syntax keyword cppSTLfunction cos
syntax keyword cppSTLfunction cosh
syntax keyword cppSTLfunction count
syntax keyword cppSTLfunction count_if
syntax keyword cppSTLfunction c_str
syntax keyword cppSTLfunction ctime
syntax keyword cppSTLfunction data
syntax keyword cppSTLfunction denorm_min
syntax keyword cppSTLfunction destroy
syntax keyword cppSTLfunction difftime
syntax keyword cppSTLfunction distance
syntax keyword cppSTLfunction div
syntax keyword cppSTLfunction empty
syntax keyword cppSTLfunction end
syntax keyword cppSTLfunction eof
syntax keyword cppSTLfunction epsilon
syntax keyword cppSTLfunction equal
syntax keyword cppSTLfunction equal_range
syntax keyword cppSTLfunction erase
syntax keyword cppSTLfunction exit
syntax keyword cppSTLfunction exp
syntax keyword cppSTLfunction fabs
syntax keyword cppSTLfunction fail
syntax keyword cppSTLfunction failure
syntax keyword cppSTLfunction fclose
syntax keyword cppSTLfunction feof
syntax keyword cppSTLfunction ferror
syntax keyword cppSTLfunction fflush
syntax keyword cppSTLfunction fgetc
syntax keyword cppSTLfunction fgetpos
syntax keyword cppSTLfunction fgets
syntax keyword cppSTLfunction fill
syntax keyword cppSTLfunction fill_n
syntax keyword cppSTLfunction find
syntax keyword cppSTLfunction find_end
syntax keyword cppSTLfunction find_first_not_of
syntax keyword cppSTLfunction find_first_of
syntax keyword cppSTLfunction find_if
syntax keyword cppSTLfunction find_last_not_of
syntax keyword cppSTLfunction find_last_of
syntax keyword cppSTLfunction first
syntax keyword cppSTLfunction flags
syntax keyword cppSTLfunction flip
syntax keyword cppSTLfunction floor
syntax keyword cppSTLfunction flush
syntax keyword cppSTLfunction fmod
syntax keyword cppSTLfunction fopen
syntax keyword cppSTLfunction for_each
syntax keyword cppSTLfunction fprintf
syntax keyword cppSTLfunction fputc
syntax keyword cppSTLfunction fputs
syntax keyword cppSTLfunction fread
syntax keyword cppSTLfunction free
syntax keyword cppSTLfunction freopen
syntax keyword cppSTLfunction frexp
syntax keyword cppSTLfunction front
syntax keyword cppSTLfunction fscanf
syntax keyword cppSTLfunction fseek
syntax keyword cppSTLfunction fsetpos
syntax keyword cppSTLfunction ftell
syntax keyword cppSTLfunction fwide
syntax keyword cppSTLfunction fwprintf
syntax keyword cppSTLfunction fwrite
syntax keyword cppSTLfunction fwscanf
syntax keyword cppSTLfunction gcount
syntax keyword cppSTLfunction generate
syntax keyword cppSTLfunction generate_n
syntax keyword cppSTLfunction get
syntax keyword cppSTLfunction get_allocator
syntax keyword cppSTLfunction getc
syntax keyword cppSTLfunction getchar
syntax keyword cppSTLfunction getenv
syntax keyword cppSTLfunction getline
syntax keyword cppSTLfunction gets
syntax keyword cppSTLfunction get_temporary_buffer
syntax keyword cppSTLfunction gmtime
syntax keyword cppSTLfunction good
syntax keyword cppSTLfunction ignore
syntax keyword cppSTLfunction imag
syntax keyword cppSTLfunction in
syntax keyword cppSTLfunction includes
syntax keyword cppSTLfunction infinity
syntax keyword cppSTLfunction inner_product
syntax keyword cppSTLfunction inplace_merge
syntax keyword cppSTLfunction insert
syntax keyword cppSTLfunction inserter
syntax keyword cppSTLfunction ios
syntax keyword cppSTLfunction ios_base
syntax keyword cppSTLfunction iostate
syntax keyword cppSTLfunction iota
syntax keyword cppSTLfunction isalnum
syntax keyword cppSTLfunction isalpha
syntax keyword cppSTLfunction iscntrl
syntax keyword cppSTLfunction isdigit
syntax keyword cppSTLfunction isgraph
syntax keyword cppSTLfunction is_heap
syntax keyword cppSTLfunction islower
syntax keyword cppSTLfunction is_open
syntax keyword cppSTLfunction isprint
syntax keyword cppSTLfunction ispunct
syntax keyword cppSTLfunction isspace
syntax keyword cppSTLfunction isupper
syntax keyword cppSTLfunction isxdigit
syntax keyword cppSTLfunction iterator_category
syntax keyword cppSTLfunction iter_swap
syntax keyword cppSTLfunction key_comp
syntax keyword cppSTLfunction labs
syntax keyword cppSTLfunction ldexp
syntax keyword cppSTLfunction ldiv
syntax keyword cppSTLfunction length
syntax keyword cppSTLfunction lexicographical_compare
syntax keyword cppSTLfunction lexicographical_compare_3way
syntax keyword cppSTLfunction llabs
syntax keyword cppSTLfunction lldiv
syntax keyword cppSTLfunction localtime
syntax keyword cppSTLfunction log
syntax keyword cppSTLfunction log10
syntax keyword cppSTLfunction longjmp
syntax keyword cppSTLfunction lower_bound
syntax keyword cppSTLfunction make_heap
syntax keyword cppSTLfunction make_pair
syntax keyword cppSTLfunction malloc
syntax keyword cppSTLfunction max
syntax keyword cppSTLfunction max_element
syntax keyword cppSTLfunction max_size
syntax keyword cppSTLfunction memchr
syntax keyword cppSTLfunction memcpy
syntax keyword cppSTLfunction mem_fun
syntax keyword cppSTLfunction mem_fun_ref
syntax keyword cppSTLfunction memmove
syntax keyword cppSTLfunction memset
syntax keyword cppSTLfunction merge
syntax keyword cppSTLfunction min
syntax keyword cppSTLfunction min_element
syntax keyword cppSTLfunction mismatch
syntax keyword cppSTLfunction mktime
syntax keyword cppSTLfunction modf
syntax keyword cppSTLfunction next_permutation
syntax keyword cppSTLfunction none
syntax keyword cppSTLfunction norm
syntax keyword cppSTLfunction not1
syntax keyword cppSTLfunction not2
syntax keyword cppSTLfunction nth_element
syntax keyword cppSTLfunction open
syntax keyword cppSTLfunction partial_sort
syntax keyword cppSTLfunction partial_sort_copy
syntax keyword cppSTLfunction partial_sum
syntax keyword cppSTLfunction partition
syntax keyword cppSTLfunction peek
syntax keyword cppSTLfunction perror
syntax keyword cppSTLfunction polar
syntax keyword cppSTLfunction pop
syntax keyword cppSTLfunction pop_back
syntax keyword cppSTLfunction pop_front
syntax keyword cppSTLfunction pop_heap
syntax keyword cppSTLfunction pow
syntax keyword cppSTLfunction power
syntax keyword cppSTLfunction precision
syntax keyword cppSTLfunction prev_permutation
syntax keyword cppSTLfunction printf
syntax keyword cppSTLfunction ptr_fun
syntax keyword cppSTLfunction push
syntax keyword cppSTLfunction push_back
syntax keyword cppSTLfunction push_front
syntax keyword cppSTLfunction push_heap
syntax keyword cppSTLfunction put
syntax keyword cppSTLfunction putback
syntax keyword cppSTLfunction putc
syntax keyword cppSTLfunction putchar
syntax keyword cppSTLfunction puts
syntax keyword cppSTLfunction qsort
syntax keyword cppSTLfunction quiet_NaN
syntax keyword cppSTLfunction raise
syntax keyword cppSTLfunction rand
syntax keyword cppSTLfunction random_sample
syntax keyword cppSTLfunction random_sample_n
syntax keyword cppSTLfunction random_shuffle
syntax keyword cppSTLfunction rbegin
syntax keyword cppSTLfunction rdbuf
syntax keyword cppSTLfunction rdstate
syntax keyword cppSTLfunction read
syntax keyword cppSTLfunction real
syntax keyword cppSTLfunction realloc
syntax keyword cppSTLfunction remove
syntax keyword cppSTLfunction remove_copy
syntax keyword cppSTLfunction remove_copy_if
syntax keyword cppSTLfunction remove_if
syntax keyword cppSTLfunction rename
syntax keyword cppSTLfunction rend
syntax keyword cppSTLfunction replace
syntax keyword cppSTLfunction replace_copy
syntax keyword cppSTLfunction replace_copy_if
syntax keyword cppSTLfunction replace_if
syntax keyword cppSTLfunction reserve
syntax keyword cppSTLfunction reset
syntax keyword cppSTLfunction resize
syntax keyword cppSTLfunction return_temporary_buffer
syntax keyword cppSTLfunction reverse
syntax keyword cppSTLfunction reverse_copy
syntax keyword cppSTLfunction rewind
syntax keyword cppSTLfunction rfind
syntax keyword cppSTLfunction rotate
syntax keyword cppSTLfunction rotate_copy
syntax keyword cppSTLfunction round_error
syntax keyword cppSTLfunction scanf
syntax keyword cppSTLfunction search
syntax keyword cppSTLfunction search_n
syntax keyword cppSTLfunction second
syntax keyword cppSTLfunction seekg
syntax keyword cppSTLfunction seekp
syntax keyword cppSTLfunction setbuf
syntax keyword cppSTLfunction set_difference
syntax keyword cppSTLfunction setf
syntax keyword cppSTLfunction set_intersection
syntax keyword cppSTLfunction setjmp
syntax keyword cppSTLfunction setlocale
syntax keyword cppSTLfunction set_new_handler
syntax keyword cppSTLfunction set_symmetric_difference
syntax keyword cppSTLfunction set_union
syntax keyword cppSTLfunction setvbuf
syntax keyword cppSTLfunction signal
syntax keyword cppSTLfunction signaling_NaN
syntax keyword cppSTLfunction sin
syntax keyword cppSTLfunction sinh
syntax keyword cppSTLfunction size
syntax keyword cppSTLfunction sort
syntax keyword cppSTLfunction sort_heap
syntax keyword cppSTLfunction splice
syntax keyword cppSTLfunction sprintf
syntax keyword cppSTLfunction sqrt
syntax keyword cppSTLfunction srand
syntax keyword cppSTLfunction sscanf
syntax keyword cppSTLfunction stable_partition
syntax keyword cppSTLfunction stable_sort
syntax keyword cppSTLfunction str
syntax keyword cppSTLfunction strcat
syntax keyword cppSTLfunction strchr
syntax keyword cppSTLfunction strcmp
syntax keyword cppSTLfunction strcoll
syntax keyword cppSTLfunction strcpy
syntax keyword cppSTLfunction strcspn
syntax keyword cppSTLfunction strerror
syntax keyword cppSTLfunction strftime
syntax keyword cppSTLfunction string
syntax keyword cppSTLfunction strlen
syntax keyword cppSTLfunction strncat
syntax keyword cppSTLfunction strncmp
syntax keyword cppSTLfunction strncpy
syntax keyword cppSTLfunction strpbrk
syntax keyword cppSTLfunction strrchr
syntax keyword cppSTLfunction strspn
syntax keyword cppSTLfunction strstr
syntax keyword cppSTLfunction strtod
syntax keyword cppSTLfunction strtof
syntax keyword cppSTLfunction strtok
syntax keyword cppSTLfunction strtol
syntax keyword cppSTLfunction strtold
syntax keyword cppSTLfunction strtoll
syntax keyword cppSTLfunction strtoul
syntax keyword cppSTLfunction strxfrm
syntax keyword cppSTLfunction substr
syntax keyword cppSTLfunction swap
syntax keyword cppSTLfunction swap_ranges
syntax keyword cppSTLfunction swprintf
syntax keyword cppSTLfunction swscanf
syntax keyword cppSTLfunction sync_with_stdio
syntax keyword cppSTLfunction system
syntax keyword cppSTLfunction tan
syntax keyword cppSTLfunction tanh
syntax keyword cppSTLfunction tellg
syntax keyword cppSTLfunction tellp
syntax keyword cppSTLfunction test
syntax keyword cppSTLfunction time
syntax keyword cppSTLfunction tmpfile
syntax keyword cppSTLfunction tmpnam
syntax keyword cppSTLfunction tolower
syntax keyword cppSTLfunction top
syntax keyword cppSTLfunction to_string
syntax keyword cppSTLfunction to_ulong
syntax keyword cppSTLfunction toupper
syntax keyword cppSTLfunction to_wstring
syntax keyword cppSTLfunction transform
syntax keyword cppSTLfunction unary_compose
syntax keyword cppSTLfunction unget
syntax keyword cppSTLfunction ungetc
syntax keyword cppSTLfunction uninitialized_copy
syntax keyword cppSTLfunction uninitialized_copy_n
syntax keyword cppSTLfunction uninitialized_fill
syntax keyword cppSTLfunction uninitialized_fill_n
syntax keyword cppSTLfunction unique
syntax keyword cppSTLfunction unique_copy
syntax keyword cppSTLfunction unsetf
syntax keyword cppSTLfunction upper_bound
syntax keyword cppSTLfunction va_arg
syntax keyword cppSTLfunction va_copy
syntax keyword cppSTLfunction va_end
syntax keyword cppSTLfunction value_comp
syntax keyword cppSTLfunction va_start
syntax keyword cppSTLfunction vfprintf
syntax keyword cppSTLfunction vfwprintf
syntax keyword cppSTLfunction vprintf
syntax keyword cppSTLfunction vsprintf
syntax keyword cppSTLfunction vswprintf
syntax keyword cppSTLfunction vwprintf
syntax keyword cppSTLfunction width
syntax keyword cppSTLfunction wprintf
syntax keyword cppSTLfunction write
syntax keyword cppSTLfunction wscanf
syntax keyword cppSTLios boolalpha
syntax keyword cppSTLios dec
syntax keyword cppSTLios defaultfloat
syntax keyword cppSTLios endl
syntax keyword cppSTLios ends
syntax keyword cppSTLios fixed
syntax keyword cppSTLios flush
syntax keyword cppSTLios get_money
syntax keyword cppSTLios get_time
syntax keyword cppSTLios hex
syntax keyword cppSTLios hexfloat
syntax keyword cppSTLios internal
syntax keyword cppSTLios noboolalpha
syntax keyword cppSTLios noshowbase
syntax keyword cppSTLios noshowpoint
syntax keyword cppSTLios noshowpos
syntax keyword cppSTLios noskipws
syntax keyword cppSTLios nounitbuf
syntax keyword cppSTLios nouppercase
syntax keyword cppSTLios oct
syntax keyword cppSTLios put_money
syntax keyword cppSTLios put_time
syntax keyword cppSTLios resetiosflags
syntax keyword cppSTLios scientific
syntax keyword cppSTLios setbase
syntax keyword cppSTLios setfill
syntax keyword cppSTLios setiosflags
syntax keyword cppSTLios setprecision
syntax keyword cppSTLios setw
syntax keyword cppSTLios showbase
syntax keyword cppSTLios showpoint
syntax keyword cppSTLios showpos
syntax keyword cppSTLios skipws
syntax keyword cppSTLios unitbuf
syntax keyword cppSTLios uppercase
"syntax keyword cppSTLios ws
syntax keyword cppSTLiterator back_insert_iterator
syntax keyword cppSTLiterator bidirectional_iterator
syntax keyword cppSTLiterator const_iterator
syntax keyword cppSTLiterator const_reverse_iterator
syntax keyword cppSTLiterator forward_iterator
syntax keyword cppSTLiterator front_insert_iterator
syntax keyword cppSTLiterator input_iterator
syntax keyword cppSTLiterator insert_iterator
syntax keyword cppSTLiterator istreambuf_iterator
syntax keyword cppSTLiterator istream_iterator
syntax keyword cppSTLiterator iterator
syntax keyword cppSTLiterator ostreambuf_iterator
syntax keyword cppSTLiterator ostream_iterator
syntax keyword cppSTLiterator output_iterator
syntax keyword cppSTLiterator random_access_iterator
syntax keyword cppSTLiterator raw_storage_iterator
syntax keyword cppSTLiterator reverse_bidirectional_iterator
syntax keyword cppSTLiterator reverse_iterator
syntax keyword cppSTLiterator_tag bidirectional_iterator_tag
syntax keyword cppSTLiterator_tag forward_iterator_tag
syntax keyword cppSTLiterator_tag input_iterator_tag
syntax keyword cppSTLiterator_tag output_iterator_tag
syntax keyword cppSTLiterator_tag random_access_iterator_tag
syntax keyword cppSTLnamespace rel_ops
syntax keyword cppSTLnamespace std
syntax keyword cppType allocator
syntax keyword cppType auto_ptr
syntax keyword cppType basic_filebuf
syntax keyword cppType basic_fstream
syntax keyword cppType basic_ifstream
syntax keyword cppType basic_iostream
syntax keyword cppType basic_istream
syntax keyword cppType basic_istringstream
syntax keyword cppType basic_ofstream
syntax keyword cppType basic_ostream
syntax keyword cppType basic_ostringstream
syntax keyword cppType basic_streambuf
syntax keyword cppType basic_string
syntax keyword cppType basic_stringbuf
syntax keyword cppType basic_stringstream
syntax keyword cppType binary_compose
syntax keyword cppType binder1st
syntax keyword cppType binder2nd
syntax keyword cppType bitset
syntax keyword cppType char_traits
syntax keyword cppType char_type
syntax keyword cppType const_mem_fun1_t
syntax keyword cppType const_mem_fun_ref1_t
syntax keyword cppType const_mem_fun_ref_t
syntax keyword cppType const_mem_fun_t
syntax keyword cppType const_pointer
syntax keyword cppType const_reference
syntax keyword cppType deque
syntax keyword cppType difference_type
syntax keyword cppType double_t
syntax keyword cppType filebuf
syntax keyword cppType first_type
syntax keyword cppType float_denorm_style
syntax keyword cppType float_round_style
syntax keyword cppType float_t
syntax keyword cppType fstream
syntax keyword cppType gslice_array
syntax keyword cppType ifstream
syntax keyword cppType imaxdiv_t
syntax keyword cppType indirect_array
syntax keyword cppType int_type
syntax keyword cppType ios_base
syntax keyword cppType iostream
syntax keyword cppType istream
syntax keyword cppType istringstream
syntax keyword cppType istrstream
syntax keyword cppType iterator_traits
syntax keyword cppType key_compare
syntax keyword cppType key_type
syntax keyword cppType list
syntax keyword cppType lldiv_t
syntax keyword cppType map
syntax keyword cppType mapped_type
syntax keyword cppType mask_array
syntax keyword cppType mem_fun1_t
syntax keyword cppType mem_fun_ref1_t
syntax keyword cppType mem_fun_ref_t
syntax keyword cppType mem_fun_t
syntax keyword cppType multimap
syntax keyword cppType multiset
syntax keyword cppType nothrow_t
syntax keyword cppType numeric_limits
syntax keyword cppType off_type
syntax keyword cppType ofstream
syntax keyword cppType ostream
syntax keyword cppType ostringstream
syntax keyword cppType ostrstream
syntax keyword cppType pair
syntax keyword cppType pointer
syntax keyword cppType pointer_to_binary_function
syntax keyword cppType pointer_to_unary_function
syntax keyword cppType pos_type
syntax keyword cppType priority_queue
syntax keyword cppType queue
syntax keyword cppType reference
syntax keyword cppType second_type
syntax keyword cppType sequence_buffer
syntax keyword cppType set
syntax keyword cppType size_type
syntax keyword cppType slice_array
syntax keyword cppType stack
syntax keyword cppType stream
syntax keyword cppType streambuf
syntax keyword cppType string
syntax keyword cppType stringbuf
syntax keyword cppType stringstream
syntax keyword cppType strstream
syntax keyword cppType strstreambuf
syntax keyword cppType temporary_buffer
syntax keyword cppType test_type
syntax keyword cppType tm
syntax keyword cppType traits_type
syntax keyword cppType type_info
syntax keyword cppType u16string
syntax keyword cppType u32string
syntax keyword cppType unary_compose
syntax keyword cppType unary_negate
syntax keyword cppType valarray
syntax keyword cppType value_compare
syntax keyword cppType value_type
syntax keyword cppType vector
syntax keyword cppType wfilebuf
syntax keyword cppType wfstream
syntax keyword cppType wifstream
syntax keyword cppType wiostream
syntax keyword cppType wistream
syntax keyword cppType wistringstream
syntax keyword cppType wofstream
syntax keyword cppType wostream
syntax keyword cppType wostringstream
syntax keyword cppType wstreambuf
syntax keyword cppType wstring
syntax keyword cppType wstringbuf
syntax keyword cppType wstringstream

syntax keyword cppSTLfunction mblen
syntax keyword cppSTLfunction mbtowc
syntax keyword cppSTLfunction wctomb
syntax keyword cppSTLfunction mbstowcs
syntax keyword cppSTLfunction wcstombs
syntax keyword cppSTLfunction mbsinit
syntax keyword cppSTLfunction btowc
syntax keyword cppSTLfunction wctob
syntax keyword cppSTLfunction mbrlen
syntax keyword cppSTLfunction mbrtowc
syntax keyword cppSTLfunction wcrtomb
syntax keyword cppSTLfunction mbsrtowcs
syntax keyword cppSTLfunction wcsrtombs

syntax keyword cppConstant MB_LEN_MAX
syntax keyword cppConstant MB_CUR_MAX
syntax keyword cppConstant __STDC_UTF_16__
syntax keyword cppConstant __STDC_UTF_32__

syntax keyword cppSTLfunction iswalnum
syntax keyword cppSTLfunction iswalpha
syntax keyword cppSTLfunction iswlower
syntax keyword cppSTLfunction iswupper
syntax keyword cppSTLfunction iswdigit
syntax keyword cppSTLfunction iswxdigit
syntax keyword cppSTLfunction iswcntrl
syntax keyword cppSTLfunction iswgraph
syntax keyword cppSTLfunction iswspace
syntax keyword cppSTLfunction iswprint
syntax keyword cppSTLfunction iswpunct
syntax keyword cppSTLfunction iswctype
syntax keyword cppSTLfunction wctype

syntax keyword cppSTLfunction towlower
syntax keyword cppSTLfunction towupper
syntax keyword cppSTLfunction towctrans
syntax keyword cppSTLfunction wctrans

syntax keyword cppSTLfunction wcstol
syntax keyword cppSTLfunction wcstoll
syntax keyword cppSTLfunction wcstoul
syntax keyword cppSTLfunction wcstoull
syntax keyword cppSTLfunction wcstof
syntax keyword cppSTLfunction wcstod
syntax keyword cppSTLfunction wcstold

syntax keyword cppSTLfunction wcscpy
syntax keyword cppSTLfunction wcsncpy
syntax keyword cppSTLfunction wcscat
syntax keyword cppSTLfunction wcsncat
syntax keyword cppSTLfunction wcsxfrm
syntax keyword cppSTLfunction wcslen
syntax keyword cppSTLfunction wcscmp
syntax keyword cppSTLfunction wcsncmp
syntax keyword cppSTLfunction wcscoll
syntax keyword cppSTLfunction wcschr
syntax keyword cppSTLfunction wcsrchr
syntax keyword cppSTLfunction wcsspn
syntax keyword cppSTLfunction wcscspn
syntax keyword cppSTLfunction wcspbrk
syntax keyword cppSTLfunction wcsstr
syntax keyword cppSTLfunction wcstok
syntax keyword cppSTLfunction wmemcpy
syntax keyword cppSTLfunction wmemmove
syntax keyword cppSTLfunction wmemcmp
syntax keyword cppSTLfunction wmemchr
syntax keyword cppSTLfunction wmemset

syntax keyword cppConstant WEOF
syntax keyword cppConstant WCHAR_MIN
syntax keyword cppConstant WCHAR_MAX

if !exists("cpp_no_cpp11")
    syntax keyword cppType max_align_t
    syntax keyword cppType type_index
    syntax keyword cppType initializer_list

    " type_traits
    syntax keyword cppType add_const
    syntax keyword cppType add_cv
    syntax keyword cppType add_lvalue_reference
    syntax keyword cppType add_pointer
    syntax keyword cppType add_rvalue_reference
    syntax keyword cppType add_volatile
    syntax keyword cppType aligned_storage
    syntax keyword cppType aligned_union
    syntax keyword cppType alignment_of
    syntax keyword cppType common_type
    syntax keyword cppType conditional
    syntax keyword cppType decay
    syntax keyword cppType enable_if
    syntax keyword cppType extent
    syntax keyword cppType integral_constant
    syntax keyword cppType is_abstract
    syntax keyword cppType is_arithmetic
    syntax keyword cppType is_array
    syntax keyword cppType is_assignable
    syntax keyword cppType is_base_of
    syntax keyword cppType is_class
    syntax keyword cppType is_compound
    syntax keyword cppType is_const
    syntax keyword cppType is_constructible
    syntax keyword cppType is_convertible
    syntax keyword cppType is_copy_assignable
    syntax keyword cppType is_copy_constructible
    syntax keyword cppType is_default_constructible
    syntax keyword cppType is_destructible
    syntax keyword cppType is_empty
    syntax keyword cppType is_enum
    syntax keyword cppType is_floating_point
    syntax keyword cppType is_function
    syntax keyword cppType is_fundamental
    syntax keyword cppType is_integral
    syntax keyword cppType is_literal_type
    syntax keyword cppType is_lvalue_reference
    syntax keyword cppType is_member_function_pointer
    syntax keyword cppType is_member_object_pointer
    syntax keyword cppType is_member_pointer
    syntax keyword cppType is_move_assignable
    syntax keyword cppType is_move_constructible
    syntax keyword cppType is_nothrow_assignable
    syntax keyword cppType is_nothrow_constructible
    syntax keyword cppType is_nothrow_copy_assignable
    syntax keyword cppType is_nothrow_copy_constructible
    syntax keyword cppType is_nothrow_default_constructible
    syntax keyword cppType is_nothrow_move_assignable
    syntax keyword cppType is_nothrow_move_constructible
    syntax keyword cppType is_object
    syntax keyword cppType is_pod
    syntax keyword cppType is_pointer
    syntax keyword cppType is_polymorphic
    syntax keyword cppType is_reference
    syntax keyword cppType is_rvalue_reference
    syntax keyword cppType is_same
    syntax keyword cppType is_scalar
    syntax keyword cppType is_signed
    syntax keyword cppType is_standard_layout
    syntax keyword cppType is_trivial
    syntax keyword cppType is_trivially_assignable
    syntax keyword cppType is_trivially_constructible
    syntax keyword cppType is_trivially_copyable
    syntax keyword cppType is_trivially_copy_assignable
    syntax keyword cppType is_trivially_copy_constructible
    syntax keyword cppType is_trivially_default_constructible
    syntax keyword cppType is_trivially_destructible
    syntax keyword cppType is_trivially_move_assignable
    syntax keyword cppType is_trivially_move_constructible
    syntax keyword cppType is_union
    syntax keyword cppType is_unsigned
    syntax keyword cppType is_void
    syntax keyword cppType is_volatile
    syntax keyword cppType make_signed
    syntax keyword cppType make_unsigned
    syntax keyword cppType rank
    syntax keyword cppType remove_all_extents
    syntax keyword cppType remove_const
    syntax keyword cppType remove_cv
    syntax keyword cppType remove_extent
    syntax keyword cppType remove_pointer
    syntax keyword cppType remove_reference
    syntax keyword cppType remove_volatile
    syntax keyword cppType result_of
    syntax keyword cppType underlying_type

    syntax keyword cppType true_type
    syntax keyword cppType false_type

    " memory
    syntax keyword cppType unique_ptr
    syntax keyword cppType shared_ptr
    syntax keyword cppType weak_ptr
    syntax keyword cppType owner_less
    syntax keyword cppType enable_shared_from_this
    syntax keyword cppExceptions bad_weak_ptr
    syntax keyword cppType default_delete
    syntax keyword cppType allocator_traits
    syntax keyword cppType allocator_type
    syntax keyword cppType allocator_arg_t
    syntax keyword cppConstant allocator_arg
    syntax keyword cppType uses_allocator
    syntax keyword cppType scoped_allocator_adaptor
    syntax keyword cppSTLfunction declare_reachable
    syntax keyword cppSTLfunction undeclare_reachable
    syntax keyword cppSTLfunction declare_no_pointers
    syntax keyword cppSTLfunction undeclare_no_pointers
    syntax keyword cppSTLfunction get_pointer_safety
    syntax keyword cppType pointer_safety
    syntax keyword cppType pointer_traits
    syntax keyword cppSTLfunction addressof
    syntax keyword cppSTLfunction align
    syntax keyword cppSTLfunction make_shared
    syntax keyword cppSTLfunction allocate_shared
    syntax keyword cppSTLfunction get_deleter

    " function object
    syntax keyword cppSTLfunction bind
    syntax keyword cppType is_bind_expression
    syntax keyword cppType is_placeholder
    syntax keyword cppConstant _1 _2 _3 _4 _5 _6 _7 _8 _9
    syntax keyword cppSTLfunction mem_fn
    syntax keyword cppSTLfunctional function
    syntax keyword cppExceptions bad_function_call
    syntax keyword cppType reference_wrapper
    syntax keyword cppSTLfunction ref cref

    " bitset
    syntax keyword cppSTLfunction all
    syntax keyword cppSTLfunction to_ullong

    " iterator
    syntax keyword cppSTLiterator move_iterator
    syntax keyword cppSTLfunction make_move_iterator
    syntax keyword cppSTLfunction next prev

    " cstdlib
    syntax keyword cppSTLfunction quick_exit
    syntax keyword cppSTLfunction _Exit
    syntax keyword cppSTLfunction at_quick_exit
    syntax keyword cppSTLfunction forward

    " chrono
    syntax keyword cppSTLnamespace chrono
    syntax keyword cppType duration
    syntax keyword cppType system_clock
    syntax keyword cppType steady_clock
    syntax keyword cppType high_resolution_clock
    syntax keyword cppType time_point
    syntax keyword cppCast duration_cast
    syntax keyword cppCast time_point_cast

    " tuple
    syntax keyword cppType tuple
    syntax keyword cppSTLfunction make_tuple
    syntax keyword cppSTLfunction tie
    syntax keyword cppSTLfunction forward_as_tuple
    syntax keyword cppSTLfunction tuple_cat
    syntax keyword cppType tuple_size tuple_element

    " utility
    syntax keyword cppSTLfunction declval
    syntax keyword cppConstant piecewise_construct
    syntax keyword cppType piecewise_construct_t
    syntax keyword cppSTLfunction move
    syntax keyword cppSTLfunction move_if_noexcept

    " Container
    syntax keyword cppType array
    syntax keyword cppType tuple
    syntax keyword cppSTLfunction cbegin
    syntax keyword cppSTLfunction cend
    syntax keyword cppSTLfunction crbegin
    syntax keyword cppSTLfunction crend
    syntax keyword cppSTLfunction shrink_to_fit
    syntax keyword cppSTLfunction emplace
    syntax keyword cppSTLfunction emplace_back
    syntax keyword cppSTLfunction emplace_front
    syntax keyword cppSTLfunction emplace_hint

    " forward_list
    syntax keyword cppType forward_list
    syntax keyword cppSTLfunction before_begin
    syntax keyword cppSTLfunction cbefore_begin
    syntax keyword cppSTLfunction insert_after
    syntax keyword cppSTLfunction emplace_after
    syntax keyword cppSTLfunction erase_after
    syntax keyword cppSTLfunction splice_after

    " unordered
    syntax keyword cppType unordered_map
    syntax keyword cppType unordered_set
    syntax keyword cppType unordered_multimap
    syntax keyword cppType unordered_multiset
    syntax keyword cppType hash
    syntax keyword cppType hasher
    syntax keyword cppType key_equal
    syntax keyword cppSTLiterator local_iterator
    syntax keyword cppSTLiterator const_local_iterator
    syntax keyword cppSTLfunction bucket_count
    syntax keyword cppSTLfunction max_bucket_count
    syntax keyword cppSTLfunction bucket_size
    syntax keyword cppSTLfunction bucket
    syntax keyword cppSTLfunction load_factor
    syntax keyword cppSTLfunction max_load_factor
    syntax keyword cppSTLfunction rehash
    syntax keyword cppSTLfunction reserve
    syntax keyword cppSTLfunction hash_function
    syntax keyword cppSTLfunction key_eq

    " algorithm
    syntax keyword cppSTLfunction all_of any_of none_of
    syntax keyword cppSTLfunction find_if_not
    syntax keyword cppSTLfunction copy_if
    syntax keyword cppSTLfunction copy_n
    syntax keyword cppSTLfunction move_backward
    syntax keyword cppSTLfunction shuffle
    syntax keyword cppSTLfunction is_partitioned
    syntax keyword cppSTLfunction partition_copy
    syntax keyword cppSTLfunction partition_point
    syntax keyword cppSTLfunction is_sorted
    syntax keyword cppSTLfunction is_sorted_until
    syntax keyword cppSTLfunction is_heap_until
    syntax keyword cppSTLfunction minmax
    syntax keyword cppSTLfunction minmax_element
    syntax keyword cppSTLfunction is_permutation
    syntax keyword cppSTLfunction itoa

    " numerics
    syntax keyword cppSTLfunction imaxabs
    syntax keyword cppSTLfunction imaxdiv
    syntax keyword cppSTLfunction remainder
    syntax keyword cppSTLfunction remquo
    syntax keyword cppSTLfunction fma
    syntax keyword cppSTLfunction fmax
    syntax keyword cppSTLfunction fmin
    syntax keyword cppSTLfunction fdim
    syntax keyword cppSTLfunction nan
    syntax keyword cppSTLfunction nanf
    syntax keyword cppSTLfunction nanl
    syntax keyword cppSTLfunction exp2
    syntax keyword cppSTLfunction expm1
    syntax keyword cppSTLfunction log1p
    syntax keyword cppSTLfunction log2
    syntax keyword cppSTLfunction cbrt
    syntax keyword cppSTLfunction hypot
    syntax keyword cppSTLfunction asinh
    syntax keyword cppSTLfunction acosh
    syntax keyword cppSTLfunction atanh
    syntax keyword cppSTLfunction erf
    syntax keyword cppSTLfunction erfc
    syntax keyword cppSTLfunction lgamma
    syntax keyword cppSTLfunction tgamma
    syntax keyword cppSTLfunction trunc
    syntax keyword cppSTLfunction round
    syntax keyword cppSTLfunction lround
    syntax keyword cppSTLfunction llround
    syntax keyword cppSTLfunction nearbyint
    syntax keyword cppSTLfunction rint
    syntax keyword cppSTLfunction lrint
    syntax keyword cppSTLfunction llrint
    syntax keyword cppSTLfunction scalbn
    syntax keyword cppSTLfunction scalbln
    syntax keyword cppSTLfunction ilogb
    syntax keyword cppSTLfunction logb
    syntax keyword cppSTLfunction nextafter
    syntax keyword cppSTLfunction nexttoward
    syntax keyword cppSTLfunction copysign
    syntax keyword cppSTLfunction fpclassify
    syntax keyword cppSTLfunction isfinite
    syntax keyword cppSTLfunction isinf
    syntax keyword cppSTLfunction isnan
    syntax keyword cppSTLfunction isnormal
    syntax keyword cppSTLfunction signbit
    syntax keyword cppConstant HUGE_VALF
    syntax keyword cppConstant HUGE_VALL
    syntax keyword cppConstant INFINITY
    syntax keyword cppConstant NAN
    syntax keyword cppConstant math_errhandling
    syntax keyword cppConstant MATH_ERRNO
    syntax keyword cppConstant MATH_ERREXCEPT
    syntax keyword cppConstant FP_NORMAL
    syntax keyword cppConstant FP_SUBNORMAL
    syntax keyword cppConstant FP_ZERO
    syntax keyword cppConstant FP_INFINITY
    syntax keyword cppConstant FP_NAN
    syntax keyword cppConstant FLT_EVAL_METHOD

    " complex
    syntax keyword cppSTLfunction proj

    " random
    syntax keyword cppType linear_congruential_engine
    syntax keyword cppType mersenne_twister_engine
    syntax keyword cppType subtract_with_carry_engine
    syntax keyword cppType discard_block_engine
    syntax keyword cppType independent_bits_engine
    syntax keyword cppType shuffle_order_engine
    syntax keyword cppType random_device
    syntax keyword cppType default_random_engine
    syntax keyword cppType minstd_rand0
    syntax keyword cppType minstd_rand
    syntax keyword cppType mt19937
    syntax keyword cppType mt19937_64
    syntax keyword cppType ranlux24_base
    syntax keyword cppType ranlux48_base
    syntax keyword cppType ranlux24
    syntax keyword cppType ranlux48
    syntax keyword cppType knuth_b
    syntax keyword cppSTLfunction generate_canonical
    syntax keyword cppType uniform_int_distribution
    syntax keyword cppType uniform_real_distribution
    syntax keyword cppType bernoulli_distribution
    syntax keyword cppType binomial_distribution
    syntax keyword cppType negative_binomial_distribution
    syntax keyword cppType geometric_distribution
    syntax keyword cppType poisson_distribution
    syntax keyword cppType exponential_distribution
    syntax keyword cppType gamma_distribution
    syntax keyword cppType weibull_distribution
    syntax keyword cppType extreme_value_distribution
    syntax keyword cppType normal_distribution
    syntax keyword cppType lognormal_distribution
    syntax keyword cppType chi_squared_distribution
    syntax keyword cppType cauchy_distribution
    syntax keyword cppType fisher_f_distribution
    syntax keyword cppType student_t_distribution
    syntax keyword cppType discrete_distribution
    syntax keyword cppType piecewise_constant_distribution
    syntax keyword cppType piecewise_linear_distribution
    syntax keyword cppType seed_seq

    " io
    syntax keyword cppSTLfunction iostream_category
    syntax keyword cppSTLenum io_errc
    syntax keyword cppSTLfunction vscanf vfscanf vsscanf
    syntax keyword cppSTLfunction snprintf vsnprintf
    syntax keyword cppSTLfunction vwscanf vfwscanf vswscanf

    " locale
    syntax keyword cppSTLfunction isblank
    syntax keyword cppSTLfunction iswblank
    syntax keyword cppType wstring_convert
    syntax keyword cppType wbuffer_convert
    syntax keyword cppType codecvt_utf8
    syntax keyword cppType codecvt_utf16
    syntax keyword cppType codecvt_utf8_utf16
    syntax keyword cppType codecvt_mode

    " atomic
    syntax keyword cppType atomic
    syntax keyword cppSTLfunction atomic_is_lock_free
    syntax keyword cppSTLfunction atomic_store
    syntax keyword cppSTLfunction atomic_store_explicit
    syntax keyword cppSTLfunction atomic_load
    syntax keyword cppSTLfunction atomic_load_explicit
    syntax keyword cppSTLfunction atomic_exchange
    syntax keyword cppSTLfunction atomic_exchange_explicit
    syntax keyword cppSTLfunction atomic_compare_exchange_weak
    syntax keyword cppSTLfunction atomic_compare_exchange_weak_explicit
    syntax keyword cppSTLfunction atomic_compare_exchange_strong
    syntax keyword cppSTLfunction atomic_compare_exchange_strong_explicit
    syntax keyword cppSTLfunction atomic_fetch_add
    syntax keyword cppSTLfunction atomic_fetch_add_explicit
    syntax keyword cppSTLfunction atomic_fetch_sub
    syntax keyword cppSTLfunction atomic_fetch_sub_explicit
    syntax keyword cppSTLfunction atomic_fetch_and
    syntax keyword cppSTLfunction atomic_fetch_and_explicit
    syntax keyword cppSTLfunction atomic_fetch_or
    syntax keyword cppSTLfunction atomic_fetch_or_explicit
    syntax keyword cppSTLfunction atomic_fetch_xor
    syntax keyword cppSTLfunction atomic_fetch_xor_explicit

    syntax keyword cppType atomic_flag
    syntax keyword cppSTLfunction atomic_flag_test_and_set
    syntax keyword cppSTLfunction atomic_flag_test_and_set_explicit
    syntax keyword cppSTLfunction atomic_flag_clear
    syntax keyword cppSTLfunction atomic_flag_clear_explicit

    syntax keyword cppType memory_order
    syntax keyword cppSTLfunction atomic_init
    syntax keyword cppSTLfunction kill_dependency
    syntax keyword cppSTLfunction atomic_thread_fence
    syntax keyword cppSTLfunction atomic_signal_fence

    " thread
    syntax keyword cppType thread
    syntax keyword cppSTLnamespace this_thread
    syntax keyword cppSTLfunction yield
    syntax keyword cppSTLfunction get_id
    syntax keyword cppSTLfunction sleep_for
    syntax keyword cppSTLfunction sleep_until

    syntax keyword cppSTLfunction joinable
    syntax keyword cppSTLfunction get_id
    syntax keyword cppSTLfunction native_handle
    syntax keyword cppSTLfunction hardware_concurrency
    syntax keyword cppSTLfunction join
    syntax keyword cppSTLfunction detach

    syntax keyword cppType mutex
    syntax keyword cppType timed_mutex
    syntax keyword cppType recursive_mutex
    syntax keyword cppType recursive_timed_mutex
    syntax keyword cppType lock_guard
    syntax keyword cppType unique_lock
    syntax keyword cppType defer_lock_t
    syntax keyword cppType try_to_lock_t
    syntax keyword cppType adopt_lock_t
    syntax keyword cppConstant defer_lock try_to_lock adopt_lock
    syntax keyword cppSTLfunction try_lock lock
    syntax keyword cppSTLfunction call_once
    syntax keyword cppType once_flag
    syntax keyword cppType condition_variable
    syntax keyword cppType condition_variable_any
    syntax keyword cppSTLfunction notify_all_at_thread_exit
    syntax keyword cppSTLenum cv_status

    syntax keyword cppType promise
    syntax keyword cppType packaged_task
    syntax keyword cppType future
    syntax keyword cppType shared_future

    syntax keyword cppSTLfunction async
    syntax keyword cppSTLenum launch

    syntax keyword cppSTLenum future_status
    syntax keyword cppSTLenum future_errc
    syntax keyword cppType future_error
    syntax keyword cppSTLfunction future_category

    " string
    syntax keyword cppSTLfunction stoi
    syntax keyword cppSTLfunction stol
    syntax keyword cppSTLfunction stoll
    syntax keyword cppSTLfunction stoul
    syntax keyword cppSTLfunction stoull
    syntax keyword cppSTLfunction stof
    syntax keyword cppSTLfunction stod
    syntax keyword cppSTLfunction stold

    " ratio
    syntax keyword cppType ratio
    syntax keyword cppType yocto
    syntax keyword cppType zepto
    syntax keyword cppType atto
    syntax keyword cppType femto
    syntax keyword cppType pico
    syntax keyword cppType nano
    syntax keyword cppType micro
    syntax keyword cppType milli
    syntax keyword cppType centi
    syntax keyword cppType deci
    syntax keyword cppType deca
    syntax keyword cppType hecto
    syntax keyword cppType kilo
    syntax keyword cppType mega
    syntax keyword cppType giga
    syntax keyword cppType tera
    syntax keyword cppType peta
    syntax keyword cppType exa
    syntax keyword cppType zetta
    syntax keyword cppType yotta
    syntax keyword cppType ratio_add
    syntax keyword cppType ratio_subtract
    syntax keyword cppType ratio_multiply
    syntax keyword cppType ratio_divide
    syntax keyword cppType ratio_equal
    syntax keyword cppType ratio_not_equal
    syntax keyword cppType ratio_less
    syntax keyword cppType ratio_less_equal
    syntax keyword cppType ratio_greater
    syntax keyword cppType ratio_greater_equal

    " limits
    syntax keyword cppSTLfunction lowest

    " cuchar
    syntax keyword cppSTLfunction mbrtoc16
    syntax keyword cppSTLfunction c16rtomb
    syntax keyword cppSTLfunction mbrtoc32
    syntax keyword cppSTLfunction c32rtomb

    " cinttypes
    syntax keyword cppSTLfunction strtoimax
    syntax keyword cppSTLfunction strtoumax
    syntax keyword cppSTLfunction wcstoimax
    syntax keyword cppSTLfunction wcstoumax

    syntax keyword cppType nanoseconds
    syntax keyword cppType microseconds
    syntax keyword cppType milliseconds
    syntax keyword cppType seconds
    syntax keyword cppType minutes
    syntax keyword cppType hours

    " regex
    syntax keyword cppType regex
    syntax keyword cppType wregex
    syntax keyword cppType basic_regex
    syntax keyword cppType sub_match
    syntax keyword cppType match_results
    syntax keyword cppType regex_iterator
    syntax keyword cppType regex_token_iterator
    syntax keyword cppType regex_error
    syntax keyword cppType regex_traits

    syntax keyword cppSTLfunction regex_match
    syntax keyword cppSTLfunction regex_search
    syntax keyword cppSTLfunction regex_replace

    syntax keyword cppSTLfunction mark_count
    syntax keyword cppSTLfunction getloc
    syntax keyword cppSTLfunction imbue

    syntax keyword cppSTLnamespace regex_constants
    syntax keyword cppType syntax_option_type
    syntax keyword cppType match_flag_type
    syntax keyword cppType error_type

    syntax keyword cppConstant icase
    syntax keyword cppConstant nosubs
    syntax keyword cppConstant optimize
    syntax keyword cppConstant collate
    syntax keyword cppConstant ECMAScript
    syntax keyword cppConstant basic
    syntax keyword cppConstant extended
    syntax keyword cppConstant awk
    syntax keyword cppConstant grep
    syntax keyword cppConstant egrep

    syntax keyword cppConstant match_default
    syntax keyword cppConstant match_not_bol
    syntax keyword cppConstant match_not_eol
    syntax keyword cppConstant match_not_bow
    syntax keyword cppConstant match_not_eow
    syntax keyword cppConstant match_any
    syntax keyword cppConstant match_not_null
    syntax keyword cppConstant match_continuous
    syntax keyword cppConstant match_prev_avail
    syntax keyword cppConstant format_default
    syntax keyword cppConstant format_sed
    syntax keyword cppConstant format_no_copy
    syntax keyword cppConstant format_first_only

    syntax keyword cppConstant error_collate
    syntax keyword cppConstant error_ctype
    syntax keyword cppConstant error_escape
    syntax keyword cppConstant error_backref
    syntax keyword cppConstant error_brack
    syntax keyword cppConstant error_paren
    syntax keyword cppConstant error_brace
    syntax keyword cppConstant error_badbrace
    syntax keyword cppConstant error_range
    syntax keyword cppConstant error_space
    syntax keyword cppConstant error_badrepeat
    syntax keyword cppConstant error_complexity
    syntax keyword cppConstant error_stack

endif " C++11

if !exists("cpp_no_cpp14")
    " dynarray
    syntax keyword cppType dynarray

    " thread
    syntax keyword cppType shared_timed_mutex
    syntax keyword cppType shared_lock
    syntax keyword cppSTLfunction try_lock_for
    syntax keyword cppSTLfunction try_lock_until
    syntax keyword cppSTLfunction try_lock_shared_for
    syntax keyword cppSTLfunction try_lock_shared_until
    syntax keyword cppSTLfunction unlock_shared

    " memory
    syntax keyword cppSTLfunction make_unique

    " utility
    syntax keyword cppType integer_sequence
    syntax keyword cppType index_sequence_for
    syntax keyword cppType make_integer_sequence
    syntax keyword cppType make_index_sequence
    syntax keyword cppSTLfunction exchange

endif " C++14

if !exists("cpp_no_cpp17")
    " optional
    syntax keyword cppType optional
    syntax keyword cppSTLfunction value_or
    syntax keyword cppSTLfunction make_optional
    syntax keyword cppExceptions bad_optional_access
    syntax keyword cppType nullopt_t
    syntax keyword cppConstant nullopt

    " any
    syntax keyword cppCast any_cast
    syntax keyword cppExceptions bad_any_cast

    " variant
    syntax keyword cppType variant
    syntax keyword cppType monostate
    syntax keyword cppExceptions bad_variant_access
    syntax keyword cppType variant_size
    syntax keyword cppConstant variant_size_v
    syntax keyword cppType variant_alternative
    syntax keyword cppConstant variant_alternative_t
    syntax keyword cppConstant variant_npos
    syntax keyword cppSTLfunction holds_alternative
    syntax keyword cppSTLfunction get_if
    syntax keyword cppSTLfunction visit
    syntax keyword cppSTLfunction valueless_by_exception

    " string_view
    syntax keyword cppType basic_string_view
    syntax keyword cppType string_view
    syntax keyword cppType u8string_view
    syntax keyword cppType u16string_view
    syntax keyword cppType u32string_view
    syntax keyword cppType wstring_view
    syntax keyword cppSTLfunction remove_prefix
    syntax keyword cppSTLfunction remove_suffix
    syntax keyword cppSTLfunction starts_with
    syntax keyword cppSTLfunction ends_with

    " thread
    syntax keyword cppType shared_mutex
    syntax keyword cppType lock_shared, try_lock_shared
    syntax keyword cppType scoped_lock

    " tuple
    syntax keyword cppSTLfunction make_from_tuple
    syntax keyword cppSTLfunction apply

    " type_traits
    syntax keyword cppType bool_constant
    syntax keyword cppType add_const_t
    syntax keyword cppType add_cv_t
    syntax keyword cppType add_lvalue_reference_t
    syntax keyword cppType add_pointer_t
    syntax keyword cppType add_rvalue_reference_t
    syntax keyword cppType add_volatile_t
    syntax keyword cppType aligned_storage_t
    syntax keyword cppType aligned_union_t
    syntax keyword cppConstant alignment_of_v
    syntax keyword cppType common_type_t
    syntax keyword cppType conditional_t
    syntax keyword cppType decay_t
    syntax keyword cppType enable_if_t
    syntax keyword cppConstant extent_v
    syntax keyword cppConstant is_abstract_v
    syntax keyword cppConstant is_arithmetic_v
    syntax keyword cppConstant is_array_v
    syntax keyword cppConstant is_assignable_v
    syntax keyword cppConstant is_base_of_v
    syntax keyword cppConstant is_class_v
    syntax keyword cppConstant is_compound_v
    syntax keyword cppConstant is_const_v
    syntax keyword cppConstant is_constructible_v
    syntax keyword cppConstant is_convertible_v
    syntax keyword cppConstant is_copy_assignable_v
    syntax keyword cppConstant is_copy_constructible_v
    syntax keyword cppConstant is_default_constructible_v
    syntax keyword cppConstant is_destructible_v
    syntax keyword cppConstant is_empty_v
    syntax keyword cppConstant is_enum_v
    syntax keyword cppConstant is_floating_point_v
    syntax keyword cppConstant is_function_v
    syntax keyword cppConstant is_fundamental_v
    syntax keyword cppConstant is_integral_v
    syntax keyword cppConstant is_literal_type_v
    syntax keyword cppConstant is_lvalue_reference_v
    syntax keyword cppConstant is_member_function_pointer_v
    syntax keyword cppConstant is_member_object_pointer_v
    syntax keyword cppConstant is_member_pointer_v
    syntax keyword cppConstant is_move_assignable_v
    syntax keyword cppConstant is_move_constructible_v
    syntax keyword cppConstant is_nothrow_assignable_v
    syntax keyword cppConstant is_nothrow_constructible_v
    syntax keyword cppConstant is_nothrow_copy_assignable_v
    syntax keyword cppConstant is_nothrow_copy_constructible_v
    syntax keyword cppConstant is_nothrow_default_constructible_v
    syntax keyword cppConstant is_nothrow_move_assignable_v
    syntax keyword cppConstant is_nothrow_move_constructible_v
    syntax keyword cppConstant is_object_v
    syntax keyword cppConstant is_pod_v
    syntax keyword cppConstant is_pointer_v
    syntax keyword cppConstant is_polymorphic_v
    syntax keyword cppConstant is_reference_v
    syntax keyword cppConstant is_rvalue_reference_v
    syntax keyword cppConstant is_same_v
    syntax keyword cppConstant is_scalar_v
    syntax keyword cppConstant is_signed_v
    syntax keyword cppConstant is_standard_layout_v
    syntax keyword cppConstant is_trivial_v
    syntax keyword cppConstant is_trivially_assignable_v
    syntax keyword cppConstant is_trivially_constructible_v
    syntax keyword cppConstant is_trivially_copyable_v
    syntax keyword cppConstant is_trivially_copy_assignable_v
    syntax keyword cppConstant is_trivially_copy_constructible_v
    syntax keyword cppConstant is_trivially_default_constructible_v
    syntax keyword cppConstant is_trivially_destructible_v
    syntax keyword cppConstant is_trivially_move_assignable_v
    syntax keyword cppConstant is_trivially_move_constructible_v
    syntax keyword cppConstant is_union_v
    syntax keyword cppConstant is_unsigned_v
    syntax keyword cppConstant is_void_v
    syntax keyword cppConstant is_volatile_v
    syntax keyword cppType make_signed_t
    syntax keyword cppType make_unsigned_t
    syntax keyword cppConstant rank_v
    syntax keyword cppType remove_all_extents_t
    syntax keyword cppType remove_const_t
    syntax keyword cppType remove_cv_t
    syntax keyword cppType remove_extent_t
    syntax keyword cppType remove_pointer_t
    syntax keyword cppType remove_reference_t
    syntax keyword cppType remove_volatile_t
    syntax keyword cppType result_of_t
    syntax keyword cppType underlying_type_t
    syntax keyword cppType is_null_pointer
    syntax keyword cppConstant is_null_pointer_v
    syntax keyword cppType has_unique_object_representations
    syntax keyword cppType has_strong_structural_equality
    syntax keyword cppConstant has_unique_object_representations_v
    syntax keyword cppConstant has_strong_structural_equality_v
    syntax keyword cppType is_final
    syntax keyword cppConstant is_final_v
    syntax keyword cppType is_aggregate
    syntax keyword cppConstant is_aggregate_v
    syntax keyword cppType is_bounded_array
    syntax keyword cppType is_unbounded_array
    syntax keyword cppConstant is_bounded_array_v
    syntax keyword cppConstant is_unbounded_array_v
    syntax keyword cppType is_swappable_with
    syntax keyword cppType is_swappable
    syntax keyword cppType is_nothrow_swappable_with
    syntax keyword cppType is_nothrow_swappable
    syntax keyword cppConstant is_swappable_with_v
    syntax keyword cppConstant is_swappable_v
    syntax keyword cppConstant is_nothrow_swappable_with_v
    syntax keyword cppConstant is_nothrow_swappable_v
    syntax keyword cppType is_layout_compatible
    syntax keyword cppConstant is_layout_compatible_v

    syntax keyword cppType is_invocable
    syntax keyword cppType is_invocable_r
    syntax keyword cppType is_nothrow_invocable
    syntax keyword cppType is_nothrow_invocable_r

    syntax keyword cppConstant is_invocable_v
    syntax keyword cppConstant is_invocable_r_v
    syntax keyword cppConstant is_nothrow_invocable_v
    syntax keyword cppConstant is_nothrow_invocable_r_v

    syntax keyword cppType remove_cvref
    syntax keyword cppType remove_cvref_t
    syntax keyword cppType invoke_result
    syntax keyword cppType invoke_result_t
    syntax keyword cppSTLfunction is_constant_evaluated
    syntax keyword cppType void_t

    " utility
    syntax keyword cppSTLfunction as_const
    syntax keyword cppType in_place_t
    syntax keyword cppConstant in_place
    syntax keyword cppConstant in_place_type
    syntax keyword cppConstant in_place_index
    syntax keyword cppType in_place_t
    syntax keyword cppType in_place_type_t
    syntax keyword cppType in_place_index_t

    " Algorithm
    syntax keyword cppSTLfunction for_each_n
    syntax keyword cppSTLfunction sample
    syntax keyword cppSTLfunction clamp
endif " C++17

hi def link cppSTLfunction     Function
hi def link cppSTLfunctional   Type
hi def link cppSTLnamespace    Constant
hi def link cppSTLiterator     Type
hi def link cppSTLiterator_tag Type
hi def link cppSTLenum         Type
hi def link cppSTLios          Function
